<?php
// $Id$

/**
 * @file
 * A module providing an interface to the Oral History Metadata Synchronizer.
 *
 * This module provides a template for the "OHMS audio"
 * content type, as well as a hook to save the OHMS
 * XML into a file for use by the OHMS Player PHP code.
 */

/**
 * Implements hook_help().
 */
function ohms_adapter_help($path, $arg) {
  if ($path == 'admin/help#ohms_adapter') {
    return t('Oral History Metadata Synchronizer adapter module.');
  }
}

 /**
  * Implements hook_theme().
  */
function ohms_adapter_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__ohms_audio'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--ohms_audio',
    'path' => drupal_get_path('module', 'ohms_adapter') . '/templates',
   );
  return $theme;
}

/**
 * Implements hook_node_postsave().
 */
function ohms_adapter_node_postsave($node, $op) {
  if ($node->type == "ohms_audio") {
    $filename = field_get_items("node", $node, 'field_ohms_filename')[0]['value'];
    $xmlFilePath = $_SERVER['DOCUMENT_ROOT']."/sites/default/files/ohms/".$filename;
    
    if ($op != "delete") {
      $xml = field_get_items('node', $node, 'field_ohms_xml')[0]['value'];

      # hack to deal with OHMS Player's inability to deal with qualified elements

      $xml = str_replace('xmlns:ohms="https://www.weareavp.com/nunncenter/ohms"', 'xmlns="https://www.weareavp.com/nunncenter/ohms"', $xml);
      $xml = str_replace("<ohms:", "<", $xml);
      $xml = str_replace("</ohms:", "</", $xml);
     
      $xmlFileHandle = fopen($xmlFilePath, 'w');
      if ($xmlFileHandle) {
        watchdog('ohms_adapter_notice', "Writing XML to file path {$xmlFilePath}.");

        fwrite($xmlFileHandle, $xml);
        fclose($xmlFileHandle);
      } else {
        watchdog('ohms_adapter_error', "The file path {$xmlFilePath} couldn't be opened for writing.");
      }
    } else {
      if (!unlink($xmlFilePath)) {
        watchdog('ohms_adapter_error', "Failed to remove {$filename} on delete of node {$node->title}.");
      } 
    }
  }
}
